---
version: "2.1"
services:
  ubuntu-server:
    image: nicholaswilde/ubuntu-server:latest
    container_name: ubuntu-server-default
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 3000:3000
    restart: unless-stopped
